# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = 'ubuntu/jammy64'
require 'json'

Vagrant.configure("2") do |config|
  keys = File.read('./variables.json')
  parameters = JSON.parse(keys)
  vbox_variables = parameters['vbox_variables'] # Variables
  config.vm.box = vbox_variables['image']
  config.vm.network :forwarded_port, guest: 22, host: 3200, id: 'ssh'

  config.vm.provider :virtualbox do |vb|
    vb.gui = true
    vb.memory = vbox_variables['ram']
    vb.cpus = vbox_variables['cpus']
  end
end
